{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.guava",
    "module": "guava",
    "version": "HEAD-android-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3",
      "buildId": "Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)"
    }
  },
  "variants": [
    {
      "name": "jdk6ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": "6",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava-parent",
          "version": {
            "requires": "HEAD-android-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.guava",
          "module": "failureaccess",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305"
        },
        {
          "group": "org.checkerframework",
          "module": "checker-compat-qual"
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations"
        },
        {
          "group": "com.google.j2objc",
          "module": "j2objc-annotations"
        }
      ],
      "files": [
        {
          "name": "guava-HEAD-android-SNAPSHOT.jar",
          "url": "guava-HEAD-android-SNAPSHOT.jar"
        }
      ],
      "capabilities": [
        {
          "group": "com.google.guava",
          "name": "guava",
          "version": "HEAD-android-SNAPSHOT"
        },
        {
          "group": "com.google.collections",
          "name": "google-collections",
          "version": "HEAD-android-SNAPSHOT"
        },
        {
          "group": "com.google.guava",
          "name": "listenablefuture",
          "version": "1.0"
        }
      ]
    },
    {
      "name": "jdk6RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": "6",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava-parent",
          "version": {
            "requires": "HEAD-android-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.guava",
          "module": "failureaccess",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305"
        },
        {
          "group": "org.checkerframework",
          "module": "checker-compat-qual"
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations"
        }
      ],
      "files": [
        {
          "name": "guava-HEAD-android-SNAPSHOT.jar",
          "url": "guava-HEAD-android-SNAPSHOT.jar"
        }
      ],
      "capabilities": [
        {
          "group": "com.google.guava",
          "name": "guava",
          "version": "HEAD-android-SNAPSHOT"
        },
        {
          "group": "com.google.collections",
          "name": "google-collections",
          "version": "HEAD-android-SNAPSHOT"
        },
        {
          "group": "com.google.guava",
          "name": "listenablefuture",
          "version": "1.0"
        }
      ]
    },
    {
      "name": "jdk8ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": "8",
        "org.gradle.jvm.environment": "desktop",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava-parent",
          "version": {
            "requires": "HEAD-jre-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.guava",
          "module": "failureaccess",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305"
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual"
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations"
        },
        {
          "group": "com.google.j2objc",
          "module": "j2objc-annotations"
        }
      ],
      "files": [
        {
          "name": "guava-HEAD-jre-SNAPSHOT.jar",
          "url": "../HEAD-jre-SNAPSHOT/guava-HEAD-jre-SNAPSHOT.jar"
        }
      ],
      "capabilities": [
        {
          "group": "com.google.guava",
          "name": "guava",
          "version": "HEAD-android-SNAPSHOT"
        },
        {
          "group": "com.google.collections",
          "name": "google-collections",
          "version": "HEAD-android-SNAPSHOT"
        },
        {
          "group": "com.google.guava",
          "name": "listenablefuture",
          "version": "1.0"
        }
      ]
    },
    {
      "name": "jdk8RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": "8",
        "org.gradle.jvm.environment": "desktop",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava-parent",
          "version": {
            "requires": "HEAD-jre-SNAPSHOT"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "com.google.guava",
          "module": "failureaccess",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305"
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual"
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations"
        }
      ],
      "files": [
        {
          "name": "guava-HEAD-jre-SNAPSHOT.jar",
          "url": "../HEAD-jre-SNAPSHOT/guava-HEAD-jre-SNAPSHOT.jar"
        }
      ],
      "capabilities": [
        {
          "group": "com.google.guava",
          "name": "guava",
          "version": "HEAD-android-SNAPSHOT"
        },
        {
          "group": "com.google.collections",
          "name": "google-collections",
          "version": "HEAD-android-SNAPSHOT"
        },
        {
          "group": "com.google.guava",
          "name": "listenablefuture",
          "version": "1.0"
        }
      ]
    }
  ]
}
